# -*- coding: utf-8 -*-
"""Assgnment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PC4pO0pPXc9IYc6UUAa3waAPZyQcF8IU
"""

# Build a function for finding if a number is prime or not

# Program to check if a number is prime or not

# num = 407

# To take input from the user
num = int(input("Enter a number: "))

# prime numbers are greater than 1
if num > 1:
   # check for factors
   for i in range(2,num):
       if (num % i) == 0:
           print(num,"is not a prime number")
           print(i,"times",num//i,"is",num)
           break
   else:
       print(num,"is a prime number")
       
# if input number is less than
# or equal to 1, it is not prime
else:
   print(num,"is not a prime number")

n = int(input("Enter a number = "))

if n > 1:
  for i in range(2,n):
    if(n % i) == 0:
      print("It is not a prime number")
      print(i,"times",n//i,"is",n)
      break

  else:
    print("It is a prime number")

else:
  print("It is not a prime number")

m = int(input("Number= "))

if m > 1:
  for i in range(2,m):
    if (m % i) == 0:
      print(m,"is not prime number")
      break

  else:
    print(m,"is prime number")

else:
  print(m,"is not prime number")