# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1809FMgTyIKSeBl1eN1G6eLVYMR82ut-p
"""

# Assignment 3

print("Hello Pilot...!! Please give the flight detals \n")

altitude = int(input("The current height of the aircraft is = "))

height = 1000

print("\nSince the height of the aircraft is "+str(altitude)+ " ft. , therefore\n ")

if(altitude <= 1000):
  print("You can land on runway safely.")

elif(altitude > 1000 and altitude <=5000):
  print("Bring down the aircraft to 1000 ft. height")

else:
  print("Take a round and try later")


print("\nThank You...!!")

print("Hello Pilot...!! Please give the flight detals \n")

altitude = int(input("The current height of the aircraft is = "))

height = 1000

print("\nSince the height of the aircraft is "+str(altitude)+ " ft. , therefore\n ")

if(altitude <= 1000):
  print("You can land on runway safely.")

elif(altitude > 1000 and altitude <=5000):
  print("Bring down the aircraft to 1000 ft. height")

else:
  print("Take a round and try later")


print("\nThank You...!!")

