# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LetXbpl-VhzdWq-tjINArw9VaCqrzAmf
"""

import random

maxTicketsAvailable = int(input("Enter the number of participants = "))

participants = []

for temp in range(maxTicketsAvailable):
  st = "\nEnter the participant name "+ str(temp + 1) + " - "
  name = input(st)
  participants.append(name)

print("\nAll the participants are - ",participants)

n = random.randint(0,maxTicketsAvailable-1)

print("\nThe winner of lottery - ",participants[n])

