# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdnpv_VFpHxGHMsPWsfknQIRkfomBLXH
"""

a = int(input("first number = "))
b = int(input("second number = "))
s1 = a + b
print("The Sum is ",s1)

c = int(input("third number = "))
d = int(input("fourth number ="))
s2 = c-d
print("The subtraction is ",s2)

e = int(input("fifth number = "))
f = int(input("sixth number = "))
m1 = e * f
print("The Multiplication is ",m1)

g = int(input("seventh number = "))
h = int(input("eighth number = "))
d1 = g / h
print("The Division is ",d1)

i = int(input("a number = "))
j = int(input("a different number = "))
d2 = i / j
d3 = int(d2)
print("This division is ",d3)

k = float(input("n1 = "))
l = float(input("n2 = "))
m2 = k * l
print("Result = ",m2)

