# -*- coding: utf-8 -*-
"""Flight Time.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dE3Q2c-YjKIP9Wr69xAy6U2CpQ0qlFOj
"""

print("WELCOME TO MANIK JAIN AIR TRAVELS\n")

str(input("Your Boarding Place - "))
str(input("\nYour Destination Place - "))

d = int(input("\nEnter the distance in kilometres (km) = "))
s = int(input("\nEnter the speed in kilometre per hour (kmph) = "))

t = d / s

print("\nThe time taken by flight in hours = ",t)

