# -*- coding: utf-8 -*-
"""Open Weather Map API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111N9uBUuJaZRQ2ThMvQEInnh2RGgGUi1
"""

import requests
from tkinter import *
import math

city_name = "Saharanpur,India"
api_key = "b74fcd4ca4ce42617e8340903284f608"

def get_weather(api_key, city):
  url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}"

  response = requests.get(url).json()

  temp = response['main']['temp']
  temp = math.floor(temp-273.15)

  feels_like = response['main']['feels_like']
  feels_like = math.floor(feels_like-273.15)

  humidity = response['main']['humidity']

  return{
      'temp': temp,
      'feels_like': feels_like,
      'humidity': humidity
  }

  # print(response)
  # print("\nActual Temp. in Celcius: ",temp)
  # print("\nTemp. in Celcius which we feels like: ",feels_like)
  # print("\nHumidity: ",humidity)

weather = get_weather(api_key, city_name)

print("Actual temperature in Saharanpur in Celcius: ",weather['temp'])
print("\nTemperature in Celcius which we feels in Saharanpur: ",weather['feels_like'])
print("\nHumidity: ",weather['humidity'])

